// templates/react-ts-v2/src/options/App.tsx
import React, { useCallback } from 'react'
import '../style/options.less'

const chromeExtensionUrl = 'https://developer.chrome.com/docs/extensions/'

function App() {
  const goToExtensionDoc = useCallback(() => {
    window.open(chromeExtensionUrl)
  }, [])

  return (
    <div className="container">
      <div className="title">create-crx-app</div>
      <div className="start" onClick={goToExtensionDoc}>
        Getting Chrome Extension Start &nbsp; <div className="arrow"></div>
      </div>
    </div>
  )
}

export default App

// templates/vue-ts-mv2/src/options/App.vue
<template>
  <div class="container">
    <div class="title">create-crx-app</div>
    <div class="start" @click="goToExtensionDoc">
      Getting Chrome Extension Start &nbsp;
      <div class="arrow"></div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

const chromeExtensionUrl = "https://developer.chrome.com/docs/extensions/";

export default defineComponent({
  name: "App",
  methods: {
    goToExtensionDoc() {
      window.open(chromeExtensionUrl);
    },
  },
});
</script>

<style lang="less" scoped>
@import "../style/options.less";
</style>
